services:
  - type: web
    name: chatpata-tracer
    runtime: python
    buildCommand: "echo build"
    startCommand: python3 amir-tracer-server.py
    envVars:
      - key: PORT
        value: 10000
